# Generated by Django 4.2.3 on 2023-09-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifeplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField(max_length=4)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lifeplan.product')),
            ],
        ),
    ]
