# Generated by Django 4.2.3 on 2023-10-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeplan', '0003_alter_supply_amount_alter_supply_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
