# Generated by Django 4.2.3 on 2023-10-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeplan', '0004_category_slug_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
