# Generated by Django 4.2.3 on 2023-10-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifeplan', '0005_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='lifeplan.product')),
                ('size', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='lifeplan.supply')),
            ],
        ),
    ]
