# Generated by Django 4.2.3 on 2023-10-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifeplan', '0006_productinsupply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='lifeplan.product')),
            ],
            options={
                'verbose_name_plural': 'Storage',
            },
        ),
        migrations.RemoveField(
            model_name='supply',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name_plural': 'Products in orders'},
        ),
        migrations.DeleteModel(
            name='ProductInSupply',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
