# Generated by Django 4.2.3 on 2023-10-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeplan', '0007_storage_remove_supply_product_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
