# Generated by Django 4.2.3 on 2023-11-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeplan', '0008_remove_storage_price_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_amount',
            field=models.IntegerField(default=0),
        ),
    ]
