# Generated by Django 4.2.3 on 2023-11-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeplan', '0009_alter_order_items_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_mail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
