# Generated by Django 4.2.3 on 2023-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeplan', '0011_productinorder_size_of_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_mail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
