# Generated by Django 4.2.3 on 2023-11-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeplan', '0012_alter_order_client_mail_alter_order_client_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
